apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgboost-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xgboost-api
  template:
    metadata:
      labels:
        app: xgboost-api
    spec:
      containers:
      - name: xgboost-api
        image: bniladridas/flask-xgboost-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "2Gi"
            cpu: "1"
          requests:
            nvidia.com/gpu: 1
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10